<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BF400255" ignored="0" name="login" tests="59" failures="47" timestamp="30 六月 2020 03:25:42 GMT" time="2.7" errors="0">
  <testcase name="findErroAttendace" time="1.551" classname="com.ehr.cases.ehr_attendance">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.ehr.cases.ehr_attendance.findErroAttendace(ehr_attendance.java:75)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- findErroAttendace -->
  <testcase name="fillCheckApply" time="0.0" classname="com.ehr.cases.ehr_attendance">
    <skipped/>
  </testcase> <!-- fillCheckApply -->
  <testcase name="vacationApply" time="0.0" classname="com.ehr.cases.ehr_attendance">
    <skipped/>
  </testcase> <!-- vacationApply -->
  <testcase name="getAllPageTask" time="0.0" classname="com.ehr.cases.ehr_attendance">
    <skipped/>
  </testcase> <!-- getAllPageTask -->
  <testcase name="taskTransfer" time="0.0" classname="com.ehr.cases.ehr_attendance">
    <skipped/>
  </testcase> <!-- taskTransfer -->
  <testcase name="TaskToDo" time="0.0" classname="com.ehr.cases.ehr_attendance">
    <skipped/>
  </testcase> <!-- TaskToDo -->
  <testcase name="taskCompleteBatch" time="0.0" classname="com.ehr.cases.ehr_attendance">
    <skipped/>
  </testcase> <!-- taskCompleteBatch -->
  <testcase name="ehr_link" time="0.011" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.008" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.009" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.008" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.007" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.009" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.008" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.008" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.009" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.008" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.009" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.008" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.008" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.008" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.008" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.009" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.009" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.013" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.007" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.007" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.008" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.009" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.008" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.012" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.012" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.01" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.008" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.009" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.011" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.007" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.008" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.008" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.007" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.009" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.01" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.009" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.013" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.007" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.008" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.024" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.007" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.01" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.01" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.007" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.015" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.01" classname="com.ehr.cases.ehr_links2">
    <failure type="java.lang.AssertionError" message="expected [操作成功] but found [登录已失效，请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [操作成功] but found [登录已失效，请重新登录]
	at com.ehr.cases.ehr_links2.ehr_link(ehr_links2.java:54)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- ehr_link -->
  <testcase name="ehr_link" time="0.0" classname="com.ehr.cases.ehr_links2"/>
  <testcase name="ehr_link" time="0.0" classname="com.ehr.cases.ehr_links2"/>
  <testcase name="ehr_link" time="0.0" classname="com.ehr.cases.ehr_links2"/>
  <testcase name="ehr_link" time="0.0" classname="com.ehr.cases.ehr_links2"/>
  <testcase name="ehr_link" time="0.0" classname="com.ehr.cases.ehr_links2"/>
  <testcase name="ehr_link" time="0.0" classname="com.ehr.cases.ehr_links2"/>
</testsuite> <!-- login -->
